# Generated by Django 3.0.2 on 2020-08-11 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='conf',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img', models.ImageField(upload_to='pics')),
                ('desc', models.TextField()),
                ('nooflikes', models.IntegerField(default=0)),
                ('noofloves', models.IntegerField(default=0)),
                ('noofwows', models.IntegerField(default=0)),
                ('noofsad', models.IntegerField(default=0)),
                ('noofangrey', models.IntegerField(default=0)),
                ('noofhaha', models.IntegerField(default=0)),
            ],
        ),
    ]
