# Generated by Django 3.0.2 on 2020-08-11 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='email',
            field=models.EmailField(default='example@gmail.com', max_length=254),
        ),
        migrations.AlterField(
            model_name='conf',
            name='desc',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='img',
            field=models.ImageField(null=True, upload_to='pics'),
        ),
    ]
