# Generated by Django 3.0.2 on 2020-08-14 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionapp', '0003_conf_currentdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='img',
            field=models.ImageField(default=123, upload_to='images'),
            preserve_default=False,
        ),
    ]
