# Generated by Django 3.0.2 on 2020-08-15 04:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionapp', '0007_auto_20200814_1356'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conf',
            name='image',
            field=models.ImageField(null=True, upload_to='static/images/'),
        ),
    ]
