# Generated by Django 3.0.2 on 2020-08-20 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionapp', '0009_auto_20200820_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='conf',
            name='nooflike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
