# Generated by Django 3.0.2 on 2020-08-20 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('confessionapp', '0010_conf_nooflike'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='conf',
            name='nooflike',
        ),
        migrations.AlterField(
            model_name='conf',
            name='noofangrey',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='noofhaha',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='conf',
            name='noofwows',
            field=models.IntegerField(null=True),
        ),
    ]
